파일 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,11 +13,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Cache Gradle dependencies
+      - name: Cache Gradle packages
         uses: actions/cache@v3
         with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
 
@@ -30,8 +32,8 @@ jobs:
       - name: Make gradlew executable
         run: chmod +x ./gradlew
 
-      - name: Clean and Build with Gradle
-        run: ./gradlew clean build --no-daemon -x test
+      - name: Build with Gradle
+        run: ./gradlew build --no-daemon -x test
 
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
@@ -44,25 +46,28 @@ jobs:
           EC2_HOST: ${{ secrets.EC2_HOST }}
         run: |
           # 로컬에서 원격 서버로 JAR 파일 복사
-          scp -C -o StrictHostKeyChecking=no build/libs/amcn-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ubuntu/AutoMakeCardNews/amcn-0.0.1-SNAPSHOT.jar
+          scp -o StrictHostKeyChecking=no build/libs/amcn-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ubuntu/AutoMakeCardNews/amcn-0.0.1-SNAPSHOT.jar
 
           # 원격 서버에서 애플리케이션 재시작
           ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
             cd /home/ubuntu/AutoMakeCardNews
 
             # 현재 실행 중인 JAR 프로세스 종료
-            pkill -f 'java -jar amcn-0.0.1-SNAPSHOT.jar' || true
+            pkill -f 'java -jar amcn-0.0.1-SNAPSHOT.jar'
 
             # 새 JAR 파일로 애플리케이션 실행
             nohup java -jar amcn-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
 
-            # Nginx 상태 확인 및 재시작
-            if systemctl is-active --quiet nginx
+            # Nginx 설치 확인 및 재시작
+            if ! command -v nginx &> /dev/null
             then
-              echo "Nginx is already running, restarting..."
-              sudo systemctl restart nginx
-            else
-              echo "Nginx is not running, starting..."
+              echo "Nginx could not be found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y nginx
               sudo systemctl start nginx
+              sudo systemctl enable nginx
+            else
+              echo "Nginx is already installed, restarting..."
+              sudo systemctl restart nginx
             fi
           EOF
